apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      team: packapp07
  resources:
    requests:
      storage: 3Gi
